baseurl      = "https://arvela.pt/"
languageCode = "en-US"
theme        = "beautifulhugo"
title        = "Pedro Arvela"

[params]
author     = "Pedro Arvela"
subtitle   = "DevOps Engineer"
logo       = "img/profile.jpg"
dateformat = "2 Jan, 2006"

commit     = false
rss        = true

[author]
name     = "Pedro Arvela"
email    = "jp.arvela@gmail.com"
github   = "PedroArvela"
gitlab   = "PedroArvela"
linkedIn = "PedroArvela"
medium   = "@PedroArvela"
twitter  = "PedroArvela"

[[menu.main]]
name    = "Home"
url     = "/"
weight  = 1

[[menu.main]]
name = "Blog"
url = "/post"
weight = 50

[[menu.main]]
name    = "Resume (PDF)"
url     = "/assets/pedro-arvela-resume.en.pdf"
weight  = 100
