baseurl         = "https://arvela.pt/"
languageCode    = "en-US"
theme           = "hugo-goa"

title       = "Pedro Arvela"
author      = "Pedro Arvela"

[params]
author      = "Pedro Arvela"
authorimage = "profile.jpg"
intro       = "Software Engineer"
description = "Site Reliability Engineer at Unbabel"
dateformat  = "2 Jan, 2006"

[params.social]
email       = "jp.arvela@gmail.com"
github      = "PedroArvela"
gitlab      = "PedroArvela"
linkedIn    = "PedroArvela"
medium      = "@PedroArvela"

[params.extra]
copyright   = "(c) 2017 Pedro Arvela"
highlightjs = true

[[menu.main]]
name    = "Home"
url     = "/"
weight  = 1

[[menu.main]]
name    = "Resume (PDF)"
url     = "/assets/pedro-arvela-resume.en.pdf"
weight  = 100
